package com.hr.pojo;


import java.sql.Timestamp;

/**
 * BONUS
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class Bonus implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7051540084933503087L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 津贴id */
    private Integer bonId;

    /** 职能id */
    private String majorKindId;

    /** 职能名称 */
    private String majorKindName;

    /** 职位id */
    private String majorId;

    /** 职位名称 */
    private String majorName;

    /** 职员id */
    private String humanId;

    /** 职员名称 */
    private String humanName;

    /** 津贴项？ */
    private String bonusItem;

    /** 津贴金额 */
    private Double bonusWorth;

    /** 津贴等级 */
    private String bonusDegree;

    /** 备注，评论 */
    private String remark;

    /** 登记人 */
    private String register;

    /** 审核人 */
    private String checker;

    /** 登记时间 */
    private Timestamp registTime;

    /** 审核时间 */
    private Timestamp checkTime;

    /** 审核状态 */
    private Integer checkStatus;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取津贴id
     * 
     * @return 津贴id
     */
    public Integer getBonId() {
        return this.bonId;
    }

    /**
     * 设置津贴id
     * 
     * @param bonId
     *          津贴id
     */
    public void setBonId(Integer bonId) {
        this.bonId = bonId;
    }

    /**
     * 获取职能id
     * 
     * @return 职能id
     */
    public String getMajorKindId() {
        return this.majorKindId;
    }

    /**
     * 设置职能id
     * 
     * @param majorKindId
     *          职能id
     */
    public void setMajorKindId(String majorKindId) {
        this.majorKindId = majorKindId;
    }

    /**
     * 获取职能名称
     * 
     * @return 职能名称
     */
    public String getMajorKindName() {
        return this.majorKindName;
    }

    /**
     * 设置职能名称
     * 
     * @param majorKindName
     *          职能名称
     */
    public void setMajorKindName(String majorKindName) {
        this.majorKindName = majorKindName;
    }

    /**
     * 获取职位id
     * 
     * @return 职位id
     */
    public String getMajorId() {
        return this.majorId;
    }

    /**
     * 设置职位id
     * 
     * @param majorId
     *          职位id
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId;
    }

    /**
     * 获取职位名称
     * 
     * @return 职位名称
     */
    public String getMajorName() {
        return this.majorName;
    }

    /**
     * 设置职位名称
     * 
     * @param majorName
     *          职位名称
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * 获取职员id
     * 
     * @return 职员id
     */
    public String getHumanId() {
        return this.humanId;
    }

    /**
     * 设置职员id
     * 
     * @param humanId
     *          职员id
     */
    public void setHumanId(String humanId) {
        this.humanId = humanId;
    }

    /**
     * 获取职员名称
     * 
     * @return 职员名称
     */
    public String getHumanName() {
        return this.humanName;
    }

    /**
     * 设置职员名称
     * 
     * @param humanName
     *          职员名称
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName;
    }

    /**
     * 获取津贴项？
     * 
     * @return 津贴项？
     */
    public String getBonusItem() {
        return this.bonusItem;
    }

    /**
     * 设置津贴项？
     * 
     * @param bonusItem
     *          津贴项？
     */
    public void setBonusItem(String bonusItem) {
        this.bonusItem = bonusItem;
    }

    /**
     * 获取津贴金额
     * 
     * @return 津贴金额
     */
    public Double getBonusWorth() {
        return this.bonusWorth;
    }

    /**
     * 设置津贴金额
     * 
     * @param bonusWorth
     *          津贴金额
     */
    public void setBonusWorth(Double bonusWorth) {
        this.bonusWorth = bonusWorth;
    }

    /**
     * 获取津贴等级
     * 
     * @return 津贴等级
     */
    public String getBonusDegree() {
        return this.bonusDegree;
    }

    /**
     * 设置津贴等级
     * 
     * @param bonusDegree
     *          津贴等级
     */
    public void setBonusDegree(String bonusDegree) {
        this.bonusDegree = bonusDegree;
    }

    /**
     * 获取备注，评论
     * 
     * @return 备注
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * 设置备注，评论
     * 
     * @param remark
     *          备注
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * 获取登记人
     * 
     * @return 登记人
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置登记人
     * 
     * @param register
     *          登记人
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取审核人
     * 
     * @return 审核人
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置审核人
     * 
     * @param checker
     *          审核人
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取登记时间
     * 
     * @return 登记时间
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置登记时间
     * 
     * @param registTime
     *          登记时间
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取审核时间
     * 
     * @return 审核时间
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置审核时间
     * 
     * @param checkTime
     *          审核时间
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取审核状态
     * 
     * @return 审核状态
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * 设置审核状态
     * 
     * @param checkStatus
     *          审核状态
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}