package com.hr.pojo;

/**
 * CONFIG_QUESTION_FIRST_KIND
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class ConfigQuestionFirstKind implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2431135615404698317L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 第一类题目id */
    private Integer qfkId;

    /** 第一类id */
    private String firstKindId;

    /** 第一类名称 */
    private String firstKindName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取第一类题目id
     * 
     * @return 第一类题目id
     */
    public Integer getQfkId() {
        return this.qfkId;
    }

    /**
     * 设置第一类题目id
     * 
     * @param qfkId
     *          第一类题目id
     */
    public void setQfkId(Integer qfkId) {
        this.qfkId = qfkId;
    }

    /**
     * 获取第一类id
     * 
     * @return 第一类id
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置第一类id
     * 
     * @param firstKindId
     *          第一类id
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取第一类名称
     * 
     * @return 第一类名称
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置第一类名称
     * 
     * @param firstKindName
     *          第一类名称
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}