package com.hr.pojo;

/**
 * CONFIG_FILE_THIRD_KIND
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class ConfigFileThirdKind implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5533746130030425212L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer ftkId;

    /** 第一类id */
    private String firstKindId;

    /** 第一类名称 */
    private String firstKindName;

    /** 第二类id */
    private String secondKindId;

    /** 第二类名称 */
    private String secondKindName;

    /** 第三类id */
    private String thirdKindId;

    /** 第三类名称 */
    private String thirdKindName;

    /** ？ */
    private String thirdKindSaleId;

    /** ？ */
    private String thirdKindIsRetail;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getFtkId() {
        return this.ftkId;
    }

    /**
     * 设置id
     * 
     * @param ftkId
     *          id
     */
    public void setFtkId(Integer ftkId) {
        this.ftkId = ftkId;
    }

    /**
     * 获取第一类id
     * 
     * @return 第一类id
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置第一类id
     * 
     * @param firstKindId
     *          第一类id
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取第一类名称
     * 
     * @return 第一类名称
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置第一类名称
     * 
     * @param firstKindName
     *          第一类名称
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取第二类id
     * 
     * @return 第二类id
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置第二类id
     * 
     * @param secondKindId
     *          第二类id
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取第二类名称
     * 
     * @return 第二类名称
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置第二类名称
     * 
     * @param secondKindName
     *          第二类名称
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /**
     * 获取第三类id
     * 
     * @return 第三类id
     */
    public String getThirdKindId() {
        return this.thirdKindId;
    }

    /**
     * 设置第三类id
     * 
     * @param thirdKindId
     *          第三类id
     */
    public void setThirdKindId(String thirdKindId) {
        this.thirdKindId = thirdKindId;
    }

    /**
     * 获取第三类名称
     * 
     * @return 第三类名称
     */
    public String getThirdKindName() {
        return this.thirdKindName;
    }

    /**
     * 设置第三类名称
     * 
     * @param thirdKindName
     *          第三类名称
     */
    public void setThirdKindName(String thirdKindName) {
        this.thirdKindName = thirdKindName;
    }

    /**
     * 获取？
     * 
     * @return ？
     */
    public String getThirdKindSaleId() {
        return this.thirdKindSaleId;
    }

    /**
     * 设置？
     * 
     * @param thirdKindSaleId
     *          ？
     */
    public void setThirdKindSaleId(String thirdKindSaleId) {
        this.thirdKindSaleId = thirdKindSaleId;
    }

    /**
     * 获取？
     * 
     * @return ？
     */
    public String getThirdKindIsRetail() {
        return this.thirdKindIsRetail;
    }

    /**
     * 设置？
     * 
     * @param thirdKindIsRetail
     *          ？
     */
    public void setThirdKindIsRetail(String thirdKindIsRetail) {
        this.thirdKindIsRetail = thirdKindIsRetail;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}