package com.hr.pojo;

/**
 * CONFIG_MAJOR_KIND
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class ConfigMajorKind implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3645559953209857887L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer mfkId;

    /** 职能种类id */
    private String majorKindId;

    /** 职能种类名称 */
    private String majorKindName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getMfkId() {
        return this.mfkId;
    }

    /**
     * 设置id
     * 
     * @param mfkId
     *          id
     */
    public void setMfkId(Integer mfkId) {
        this.mfkId = mfkId;
    }

    /**
     * 获取职能种类id
     * 
     * @return 职能种类id
     */
    public String getMajorKindId() {
        return this.majorKindId;
    }

    /**
     * 设置职能种类id
     * 
     * @param majorKindId
     *          职能种类id
     */
    public void setMajorKindId(String majorKindId) {
        this.majorKindId = majorKindId;
    }

    /**
     * 获取职能种类名称
     * 
     * @return 职能种类名称
     */
    public String getMajorKindName() {
        return this.majorKindName;
    }

    /**
     * 设置职能种类名称
     * 
     * @param majorKindName
     *          职能种类名称
     */
    public void setMajorKindName(String majorKindName) {
        this.majorKindName = majorKindName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}