package com.hr.pojo;

/**
 * CONFIG_MAJOR
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class ConfigMajor implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7804981229442351045L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer makId;

    /** 职能种类id */
    private String majorKindId;

    /** 职能名称 */
    private String majorKindName;

    /** 职位id */
    private String majorId;

    /** 职位名称 */
    private String majorName;

    /** ？人数 */
    private Integer testAmount;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getMakId() {
        return this.makId;
    }

    /**
     * 设置id
     * 
     * @param makId
     *          id
     */
    public void setMakId(Integer makId) {
        this.makId = makId;
    }

    /**
     * 获取职能种类id
     * 
     * @return 职能种类id
     */
    public String getMajorKindId() {
        return this.majorKindId;
    }

    /**
     * 设置职能种类id
     * 
     * @param majorKindId
     *          职能种类id
     */
    public void setMajorKindId(String majorKindId) {
        this.majorKindId = majorKindId;
    }

    /**
     * 获取职能名称
     * 
     * @return 职能名称
     */
    public String getMajorKindName() {
        return this.majorKindName;
    }

    /**
     * 设置职能名称
     * 
     * @param majorKindName
     *          职能名称
     */
    public void setMajorKindName(String majorKindName) {
        this.majorKindName = majorKindName;
    }

    /**
     * 获取职位id
     * 
     * @return 职位id
     */
    public String getMajorId() {
        return this.majorId;
    }

    /**
     * 设置职位id
     * 
     * @param majorId
     *          职位id
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId;
    }

    /**
     * 获取职位名称
     * 
     * @return 职位名称
     */
    public String getMajorName() {
        return this.majorName;
    }

    /**
     * 设置职位名称
     * 
     * @param majorName
     *          职位名称
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * 获取？人数
     * 
     * @return ？人数
     */
    public Integer getTestAmount() {
        return this.testAmount;
    }

    /**
     * 设置？人数
     * 
     * @param testAmount
     *          ？人数
     */
    public void setTestAmount(Integer testAmount) {
        this.testAmount = testAmount;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}