package com.hr.pojo;

/**
 * CONFIG_QUESTION_SECOND_KIND
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class ConfigQuestionSecondKind implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3271739613573128615L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 第二类题目id */
    private Integer qskId;

    /** 第一类id */
    private String firstKindId;

    /** 第一类名称 */
    private String firstKindName;

    /** 第二类id */
    private String secondKindId;

    /** 第二类名称 */
    private String secondKindName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取第二类题目id
     * 
     * @return 第二类题目id
     */
    public Integer getQskId() {
        return this.qskId;
    }

    /**
     * 设置第二类题目id
     * 
     * @param qskId
     *          第二类题目id
     */
    public void setQskId(Integer qskId) {
        this.qskId = qskId;
    }

    /**
     * 获取第一类id
     * 
     * @return 第一类id
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置第一类id
     * 
     * @param firstKindId
     *          第一类id
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取第一类名称
     * 
     * @return 第一类名称
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置第一类名称
     * 
     * @param firstKindName
     *          第一类名称
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取第二类id
     * 
     * @return 第二类id
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置第二类id
     * 
     * @param secondKindId
     *          第二类id
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取第二类名称
     * 
     * @return 第二类名称
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置第二类名称
     * 
     * @param secondKindName
     *          第二类名称
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}