package com.hr.pojo;

/**
 * CONFIG_PUBLIC_CHAR
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class ConfigPublicChar implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7803254203167486204L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer pbcId;

    /** 属性类别 */
    private String attributeKind;

    /** 属性名 */
    private String attributeName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getPbcId() {
        return this.pbcId;
    }

    /**
     * 设置id
     * 
     * @param pbcId
     *          id
     */
    public void setPbcId(Integer pbcId) {
        this.pbcId = pbcId;
    }

    /**
     * 获取属性类别
     * 
     * @return 属性类别
     */
    public String getAttributeKind() {
        return this.attributeKind;
    }

    /**
     * 设置属性类别
     * 
     * @param attributeKind
     *          属性类别
     */
    public void setAttributeKind(String attributeKind) {
        this.attributeKind = attributeKind;
    }

    /**
     * 获取属性名
     * 
     * @return 属性名
     */
    public String getAttributeName() {
        return this.attributeName;
    }

    /**
     * 设置属性名
     * 
     * @param attributeName
     *          属性名
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}