package com.hr.pojo;
import java.sql.Timestamp;

/**
 * ENGAGE_INTERVIEW
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class EngageInterview implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5490113359153785715L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    private Integer einId;

    /** 人名 */
    private String humanName;

    /** 面试的次数 */
    private Integer interviewAmount;

    /** ？职能ID */
    private String humanMajorKindId;

    /** ？职能名称 */
    private String humanMajorKindName;

    /** ？职位ID */
    private String humanMajorId;

    /** ？职位名 */
    private String humanMajorName;

    /** 形象等级 */
    private String imageDegree;

    /** 普通话等级 */
    private String nativeLanguageDegree;

    /** 外语等级 */
    private String foreignLanguageDegree;

    /** 应变能力等级 */
    private String responseSpeedDegree;

    /** EQ等级 */
    private String eqDegree;

    /** IQ等级 */
    private String iqDegree;

    /** 总体等级 */
    private String multiQualityDegree;

    /** 登记者 */
    private String register;

    /** 审核者 */
    private String checker;

    /** 登记时间 */
    private Timestamp registeTime;

    /** 审核时间 */
    private Timestamp checkTime;

    /** 简历ID */
    private Integer resumeId;

    /** 结果 */
    private String result;

    /** 面试评价 */
    private String interviewComment;

    /** 审核者评价 */
    private String checkComment;

    /** 面试状态 */
    private Integer interviewStatus;

    /** 审核状态 */
    private Integer checkStatus;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取ID
     * 
     * @return ID
     */
    public Integer getEinId() {
        return this.einId;
    }

    /**
     * 设置ID
     * 
     * @param einId
     *          ID
     */
    public void setEinId(Integer einId) {
        this.einId = einId;
    }

    /**
     * 获取人名
     * 
     * @return 人名
     */
    public String getHumanName() {
        return this.humanName;
    }

    /**
     * 设置人名
     * 
     * @param humanName
     *          人名
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName;
    }

    /**
     * 获取面试的次数
     * 
     * @return 面试的次数
     */
    public Integer getInterviewAmount() {
        return this.interviewAmount;
    }

    /**
     * 设置面试的次数
     * 
     * @param interviewAmount
     *          面试的次数
     */
    public void setInterviewAmount(Integer interviewAmount) {
        this.interviewAmount = interviewAmount;
    }

    /**
     * 获取？职能ID
     * 
     * @return ？职能ID
     */
    public String getHumanMajorKindId() {
        return this.humanMajorKindId;
    }

    /**
     * 设置？职能ID
     * 
     * @param humanMajorKindId
     *          ？职能ID
     */
    public void setHumanMajorKindId(String humanMajorKindId) {
        this.humanMajorKindId = humanMajorKindId;
    }

    /**
     * 获取？职能名称
     * 
     * @return ？职能名称
     */
    public String getHumanMajorKindName() {
        return this.humanMajorKindName;
    }

    /**
     * 设置？职能名称
     * 
     * @param humanMajorKindName
     *          ？职能名称
     */
    public void setHumanMajorKindName(String humanMajorKindName) {
        this.humanMajorKindName = humanMajorKindName;
    }

    /**
     * 获取？职位ID
     * 
     * @return ？职位ID
     */
    public String getHumanMajorId() {
        return this.humanMajorId;
    }

    /**
     * 设置？职位ID
     * 
     * @param humanMajorId
     *          ？职位ID
     */
    public void setHumanMajorId(String humanMajorId) {
        this.humanMajorId = humanMajorId;
    }

    /**
     * 获取？职位名
     * 
     * @return ？职位名
     */
    public String getHumanMajorName() {
        return this.humanMajorName;
    }

    /**
     * 设置？职位名
     * 
     * @param humanMajorName
     *          ？职位名
     */
    public void setHumanMajorName(String humanMajorName) {
        this.humanMajorName = humanMajorName;
    }

    /**
     * 获取形象等级
     * 
     * @return 形象等级
     */
    public String getImageDegree() {
        return this.imageDegree;
    }

    /**
     * 设置形象等级
     * 
     * @param imageDegree
     *          形象等级
     */
    public void setImageDegree(String imageDegree) {
        this.imageDegree = imageDegree;
    }

    /**
     * 获取普通话等级
     * 
     * @return 普通话等级
     */
    public String getNativeLanguageDegree() {
        return this.nativeLanguageDegree;
    }

    /**
     * 设置普通话等级
     * 
     * @param nativeLanguageDegree
     *          普通话等级
     */
    public void setNativeLanguageDegree(String nativeLanguageDegree) {
        this.nativeLanguageDegree = nativeLanguageDegree;
    }

    /**
     * 获取外语等级
     * 
     * @return 外语等级
     */
    public String getForeignLanguageDegree() {
        return this.foreignLanguageDegree;
    }

    /**
     * 设置外语等级
     * 
     * @param foreignLanguageDegree
     *          外语等级
     */
    public void setForeignLanguageDegree(String foreignLanguageDegree) {
        this.foreignLanguageDegree = foreignLanguageDegree;
    }

    /**
     * 获取应变能力等级
     * 
     * @return 应变能力等级
     */
    public String getResponseSpeedDegree() {
        return this.responseSpeedDegree;
    }

    /**
     * 设置应变能力等级
     * 
     * @param responseSpeedDegree
     *          应变能力等级
     */
    public void setResponseSpeedDegree(String responseSpeedDegree) {
        this.responseSpeedDegree = responseSpeedDegree;
    }

    /**
     * 获取EQ等级
     * 
     * @return EQ等级
     */
    public String getEqDegree() {
        return this.eqDegree;
    }

    /**
     * 设置EQ等级
     * 
     * @param eqDegree
     *          EQ等级
     */
    public void setEqDegree(String eqDegree) {
        this.eqDegree = eqDegree;
    }

    /**
     * 获取IQ等级
     * 
     * @return IQ等级
     */
    public String getIqDegree() {
        return this.iqDegree;
    }

    /**
     * 设置IQ等级
     * 
     * @param iqDegree
     *          IQ等级
     */
    public void setIqDegree(String iqDegree) {
        this.iqDegree = iqDegree;
    }

    /**
     * 获取总体等级
     * 
     * @return 总体等级
     */
    public String getMultiQualityDegree() {
        return this.multiQualityDegree;
    }

    /**
     * 设置总体等级
     * 
     * @param multiQualityDegree
     *          总体等级
     */
    public void setMultiQualityDegree(String multiQualityDegree) {
        this.multiQualityDegree = multiQualityDegree;
    }

    /**
     * 获取登记者
     * 
     * @return 登记者
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置登记者
     * 
     * @param register
     *          登记者
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取审核者
     * 
     * @return 审核者
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置审核者
     * 
     * @param checker
     *          审核者
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取登记时间
     * 
     * @return 登记时间
     */
    public Timestamp getRegisteTime() {
        return this.registeTime;
    }

    /**
     * 设置登记时间
     * 
     * @param registeTime
     *          登记时间
     */
    public void setRegisteTime(Timestamp registeTime) {
        this.registeTime = registeTime;
    }

    /**
     * 获取审核时间
     * 
     * @return 审核时间
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置审核时间
     * 
     * @param checkTime
     *          审核时间
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取简历ID
     * 
     * @return 简历ID
     */
    public Integer getResumeId() {
        return this.resumeId;
    }

    /**
     * 设置简历ID
     * 
     * @param resumeId
     *          简历ID
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * 获取结果
     * 
     * @return 结果
     */
    public String getResult() {
        return this.result;
    }

    /**
     * 设置结果
     * 
     * @param result
     *          结果
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * 获取面试评价
     * 
     * @return 面试评价
     */
    public String getInterviewComment() {
        return this.interviewComment;
    }

    /**
     * 设置面试评价
     * 
     * @param interviewComment
     *          面试评价
     */
    public void setInterviewComment(String interviewComment) {
        this.interviewComment = interviewComment;
    }

    /**
     * 获取审核者评价
     * 
     * @return 审核者评价
     */
    public String getCheckComment() {
        return this.checkComment;
    }

    /**
     * 设置审核者评价
     * 
     * @param checkComment
     *          审核者评价
     */
    public void setCheckComment(String checkComment) {
        this.checkComment = checkComment;
    }

    /**
     * 获取面试状态
     * 
     * @return 面试状态
     */
    public Integer getInterviewStatus() {
        return this.interviewStatus;
    }

    /**
     * 设置面试状态
     * 
     * @param interviewStatus
     *          面试状态
     */
    public void setInterviewStatus(Integer interviewStatus) {
        this.interviewStatus = interviewStatus;
    }

    /**
     * 获取审核状态
     * 
     * @return 审核状态
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * 设置审核状态
     * 
     * @param checkStatus
     *          审核状态
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

	@Override
	public String toString() {
		return "EngageInterview [einId=" + einId + ", humanName=" + humanName + ", interviewAmount=" + interviewAmount
				+ ", humanMajorKindId=" + humanMajorKindId + ", humanMajorKindName=" + humanMajorKindName
				+ ", humanMajorId=" + humanMajorId + ", humanMajorName=" + humanMajorName + ", imageDegree="
				+ imageDegree + ", nativeLanguageDegree=" + nativeLanguageDegree + ", foreignLanguageDegree="
				+ foreignLanguageDegree + ", responseSpeedDegree=" + responseSpeedDegree + ", eqDegree=" + eqDegree
				+ ", iqDegree=" + iqDegree + ", multiQualityDegree=" + multiQualityDegree + ", register=" + register
				+ ", checker=" + checker + ", registeTime=" + registeTime + ", checkTime=" + checkTime + ", resumeId="
				+ resumeId + ", result=" + result + ", interviewComment=" + interviewComment + ", checkComment="
				+ checkComment + ", interviewStatus=" + interviewStatus + ", checkStatus=" + checkStatus + "]";
	}

    
}