package com.hr.pojo;

/**
 * ENGAGE_EXAM_DETAILS
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class EngageExamDetails implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 8658869946267289866L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    private Integer exdId;

    /** 考试编号 */
    private String examNumber;

    /** 第一类题的ID */
    private String firstKindId;

    /** 第一类题的名称 */
    private String firstKindName;

    /** 第二类题的ID */
    private String secondKindId;

    /** 第二类题的名称 */
    private String secondKindName;

    /** 题数量 */
    private Integer questionAmount;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取ID
     * 
     * @return ID
     */
    public Integer getExdId() {
        return this.exdId;
    }

    /**
     * 设置ID
     * 
     * @param exdId
     *          ID
     */
    public void setExdId(Integer exdId) {
        this.exdId = exdId;
    }

    /**
     * 获取考试编号
     * 
     * @return 考试编号
     */
    public String getExamNumber() {
        return this.examNumber;
    }

    /**
     * 设置考试编号
     * 
     * @param examNumber
     *          考试编号
     */
    public void setExamNumber(String examNumber) {
        this.examNumber = examNumber;
    }

    /**
     * 获取第一类题的ID
     * 
     * @return 第一类题的ID
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置第一类题的ID
     * 
     * @param firstKindId
     *          第一类题的ID
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取第一类题的名称
     * 
     * @return 第一类题的名称
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置第一类题的名称
     * 
     * @param firstKindName
     *          第一类题的名称
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取第二类题的ID
     * 
     * @return 第二类题的ID
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置第二类题的ID
     * 
     * @param secondKindId
     *          第二类题的ID
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取第二类题的名称
     * 
     * @return 第二类题的名称
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置第二类题的名称
     * 
     * @param secondKindName
     *          第二类题的名称
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /**
     * 获取题数量
     * 
     * @return 题数量
     */
    public Integer getQuestionAmount() {
        return this.questionAmount;
    }

    /**
     * 设置题数量
     * 
     * @param questionAmount
     *          题数量
     */
    public void setQuestionAmount(Integer questionAmount) {
        this.questionAmount = questionAmount;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}