package com.hr.pojo;
import java.sql.Timestamp;

/**
 * ENGAGE_SUBJECTS
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class EngageSubjects implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1369594818401401893L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    private Integer subId;

    /** 一类题ID */
    private String firstKindId;

    /** 一类题名称 */
    private String firstKindName;

    /** 二类题ID */
    private String secondKindId;

    /** 二类题名称 */
    private String secondKindName;

    /** 登记者 */
    private String register;

    /** 登记时间 */
    private Timestamp registTime;

    /** 出处 */
    private String derivation;

    /** 题干 */
    private String content;

    /** a选项 */
    private String keyA;

    /** b选项 */
    private String keyB;

    /** c选项 */
    private String keyC;

    /** d选项 */
    private String keyD;

    /** e选项 */
    private String keyE;

    /** 正确答案 */
    private String correctKey;

    /** 修改人 */
    private String changer;

    /** 修改时间 */
    private Timestamp changeTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取ID
     * 
     * @return ID
     */
    public Integer getSubId() {
        return this.subId;
    }

    /**
     * 设置ID
     * 
     * @param subId
     *          ID
     */
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * 获取一类题ID
     * 
     * @return 一类题ID
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置一类题ID
     * 
     * @param firstKindId
     *          一类题ID
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取一类题名称
     * 
     * @return 一类题名称
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置一类题名称
     * 
     * @param firstKindName
     *          一类题名称
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取二类题ID
     * 
     * @return 二类题ID
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置二类题ID
     * 
     * @param secondKindId
     *          二类题ID
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取二类题名称
     * 
     * @return 二类题名称
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置二类题名称
     * 
     * @param secondKindName
     *          二类题名称
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /**
     * 获取登记者
     * 
     * @return 登记者
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置登记者
     * 
     * @param register
     *          登记者
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取登记时间
     * 
     * @return 登记时间
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置登记时间
     * 
     * @param registTime
     *          登记时间
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取出处
     * 
     * @return 出处
     */
    public String getDerivation() {
        return this.derivation;
    }

    /**
     * 设置出处
     * 
     * @param derivation
     *          出处
     */
    public void setDerivation(String derivation) {
        this.derivation = derivation;
    }

    /**
     * 获取题干
     * 
     * @return 题干
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置题干
     * 
     * @param content
     *          题干
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取a选项
     * 
     * @return a选项
     */
    public String getKeyA() {
        return this.keyA;
    }

    /**
     * 设置a选项
     * 
     * @param keyA
     *          a选项
     */
    public void setKeyA(String keyA) {
        this.keyA = keyA;
    }

    /**
     * 获取b选项
     * 
     * @return b选项
     */
    public String getKeyB() {
        return this.keyB;
    }

    /**
     * 设置b选项
     * 
     * @param keyB
     *          b选项
     */
    public void setKeyB(String keyB) {
        this.keyB = keyB;
    }

    /**
     * 获取c选项
     * 
     * @return c选项
     */
    public String getKeyC() {
        return this.keyC;
    }

    /**
     * 设置c选项
     * 
     * @param keyC
     *          c选项
     */
    public void setKeyC(String keyC) {
        this.keyC = keyC;
    }

    /**
     * 获取d选项
     * 
     * @return d选项
     */
    public String getKeyD() {
        return this.keyD;
    }

    /**
     * 设置d选项
     * 
     * @param keyD
     *          d选项
     */
    public void setKeyD(String keyD) {
        this.keyD = keyD;
    }

    /**
     * 获取e选项
     * 
     * @return e选项
     */
    public String getKeyE() {
        return this.keyE;
    }

    /**
     * 设置e选项
     * 
     * @param keyE
     *          e选项
     */
    public void setKeyE(String keyE) {
        this.keyE = keyE;
    }

    /**
     * 获取正确答案
     * 
     * @return 正确答案
     */
    public String getCorrectKey() {
        return this.correctKey;
    }

    /**
     * 设置正确答案
     * 
     * @param correctKey
     *          正确答案
     */
    public void setCorrectKey(String correctKey) {
        this.correctKey = correctKey;
    }

    /**
     * 获取修改人
     * 
     * @return 修改人
     */
    public String getChanger() {
        return this.changer;
    }

    /**
     * 设置修改人
     * 
     * @param changer
     *          修改人
     */
    public void setChanger(String changer) {
        this.changer = changer;
    }

    /**
     * 获取修改时间
     * 
     * @return 修改时间
     */
    public Timestamp getChangeTime() {
        return this.changeTime;
    }

    /**
     * 设置修改时间
     * 
     * @param changeTime
     *          修改时间
     */
    public void setChangeTime(Timestamp changeTime) {
        this.changeTime = changeTime;
    }

	@Override
	public String toString() {
		return "EngageSubjects [subId=" + subId + ", firstKindId=" + firstKindId + ", firstKindName=" + firstKindName
				+ ", secondKindId=" + secondKindId + ", secondKindName=" + secondKindName + ", register=" + register
				+ ", registTime=" + registTime + ", derivation=" + derivation + ", content=" + content + ", keyA="
				+ keyA + ", keyB=" + keyB + ", keyC=" + keyC + ", keyD=" + keyD + ", keyE=" + keyE + ", correctKey="
				+ correctKey + ", changer=" + changer + ", changeTime=" + changeTime + "]";
	}

    
}