package com.hr.pojo;
import java.sql.Timestamp;

/**
 * HUMAN_FILE_DIG
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class HumanFileDig implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -930536195639003443L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** hfdId */
    private Integer hfdId;

    /** humanId */
    private String humanId;

    /** firstKindId */
    private String firstKindId;

    /** firstKindName */
    private String firstKindName;

    /** secondKindId */
    private String secondKindId;

    /** secondKindName */
    private String secondKindName;

    /** thirdKindId */
    private String thirdKindId;

    /** thirdKindName */
    private String thirdKindName;

    /** humanName */
    private String humanName;

    /** humanAddress */
    private String humanAddress;

    /** humanPostcode */
    private String humanPostcode;

    /** humanProDesignation */
    private String humanProDesignation;

    /** humanMajorKindId */
    private String humanMajorKindId;

    /** humanMajorKindName */
    private String humanMajorKindName;

    /** humanMajorId */
    private String humanMajorId;

    /** hunmaMajorName */
    private String hunmaMajorName;

    /** humanTelephone */
    private String humanTelephone;

    /** humanMobilephone */
    private String humanMobilephone;

    /** humanBank */
    private String humanBank;

    /** humanAccount */
    private String humanAccount;

    /** humanQq */
    private String humanQq;

    /** humanEmail */
    private String humanEmail;

    /** humanHobby */
    private String humanHobby;

    /** humanSpeciality */
    private String humanSpeciality;

    /** humanSex */
    private String humanSex;

    /** humanReligion */
    private String humanReligion;

    /** humanParty */
    private String humanParty;

    /** humanNationality */
    private String humanNationality;

    /** humanRace */
    private String humanRace;

    /** humanBirthday */
    private Timestamp humanBirthday;

    /** humanBirthplace */
    private String humanBirthplace;

    /** humanAge */
    private Integer humanAge;

    /** humanEducatedDegree */
    private String humanEducatedDegree;

    /** humanEducatedYears */
    private Integer humanEducatedYears;

    /** humanEducatedMajor */
    private String humanEducatedMajor;

    /** humanSocietySecurityId */
    private String humanSocietySecurityId;

    /** humanIdCard */
    private String humanIdCard;

    /** remark */
    private String remark;

    /** salaryStandardId */
    private String salaryStandardId;

    /** salaryStandardName */
    private String salaryStandardName;

    /** salarySum */
    private Double salarySum;

    /** demandSalaraySum */
    private Double demandSalaraySum;

    /** paidSalarySum */
    private Double paidSalarySum;

    /** majorChangeAmount */
    private Integer majorChangeAmount;

    /** bonusAmount */
    private Integer bonusAmount;

    /** trainingAmount */
    private Integer trainingAmount;

    /** fileChangAmount */
    private Integer fileChangAmount;

    /** humanHistroyRecords */
    private String humanHistroyRecords;

    /** humanFamilyMembership */
    private String humanFamilyMembership;

    /** humanPicture */
    private String humanPicture;

    /** attachmentName */
    private String attachmentName;

    /** checkStatus */
    private Integer checkStatus;

    /** register */
    private String register;

    /** checker */
    private String checker;

    /** changer */
    private String changer;

    /** registTime */
    private Timestamp registTime;

    /** checkTime */
    private Timestamp checkTime;

    /** changeTime */
    private Timestamp changeTime;

    /** lastlyChangeTime */
    private Timestamp lastlyChangeTime;

    /** deleteTime */
    private Timestamp deleteTime;

    /** recoveryTime */
    private Timestamp recoveryTime;

    /** humanFileStatus */
    private Integer humanFileStatus;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取hfdId
     * 
     * @return hfdId
     */
    public Integer getHfdId() {
        return this.hfdId;
    }

    /**
     * 设置hfdId
     * 
     * @param hfdId
     */
    public void setHfdId(Integer hfdId) {
        this.hfdId = hfdId;
    }

    /**
     * 获取humanId
     * 
     * @return humanId
     */
    public String getHumanId() {
        return this.humanId;
    }

    /**
     * 设置humanId
     * 
     * @param humanId
     */
    public void setHumanId(String humanId) {
        this.humanId = humanId;
    }

    /**
     * 获取firstKindId
     * 
     * @return firstKindId
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置firstKindId
     * 
     * @param firstKindId
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取firstKindName
     * 
     * @return firstKindName
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置firstKindName
     * 
     * @param firstKindName
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取secondKindId
     * 
     * @return secondKindId
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置secondKindId
     * 
     * @param secondKindId
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取secondKindName
     * 
     * @return secondKindName
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置secondKindName
     * 
     * @param secondKindName
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /**
     * 获取thirdKindId
     * 
     * @return thirdKindId
     */
    public String getThirdKindId() {
        return this.thirdKindId;
    }

    /**
     * 设置thirdKindId
     * 
     * @param thirdKindId
     */
    public void setThirdKindId(String thirdKindId) {
        this.thirdKindId = thirdKindId;
    }

    /**
     * 获取thirdKindName
     * 
     * @return thirdKindName
     */
    public String getThirdKindName() {
        return this.thirdKindName;
    }

    /**
     * 设置thirdKindName
     * 
     * @param thirdKindName
     */
    public void setThirdKindName(String thirdKindName) {
        this.thirdKindName = thirdKindName;
    }

    /**
     * 获取humanName
     * 
     * @return humanName
     */
    public String getHumanName() {
        return this.humanName;
    }

    /**
     * 设置humanName
     * 
     * @param humanName
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName;
    }

    /**
     * 获取humanAddress
     * 
     * @return humanAddress
     */
    public String getHumanAddress() {
        return this.humanAddress;
    }

    /**
     * 设置humanAddress
     * 
     * @param humanAddress
     */
    public void setHumanAddress(String humanAddress) {
        this.humanAddress = humanAddress;
    }

    /**
     * 获取humanPostcode
     * 
     * @return humanPostcode
     */
    public String getHumanPostcode() {
        return this.humanPostcode;
    }

    /**
     * 设置humanPostcode
     * 
     * @param humanPostcode
     */
    public void setHumanPostcode(String humanPostcode) {
        this.humanPostcode = humanPostcode;
    }

    /**
     * 获取humanProDesignation
     * 
     * @return humanProDesignation
     */
    public String getHumanProDesignation() {
        return this.humanProDesignation;
    }

    /**
     * 设置humanProDesignation
     * 
     * @param humanProDesignation
     */
    public void setHumanProDesignation(String humanProDesignation) {
        this.humanProDesignation = humanProDesignation;
    }

    /**
     * 获取humanMajorKindId
     * 
     * @return humanMajorKindId
     */
    public String getHumanMajorKindId() {
        return this.humanMajorKindId;
    }

    /**
     * 设置humanMajorKindId
     * 
     * @param humanMajorKindId
     */
    public void setHumanMajorKindId(String humanMajorKindId) {
        this.humanMajorKindId = humanMajorKindId;
    }

    /**
     * 获取humanMajorKindName
     * 
     * @return humanMajorKindName
     */
    public String getHumanMajorKindName() {
        return this.humanMajorKindName;
    }

    /**
     * 设置humanMajorKindName
     * 
     * @param humanMajorKindName
     */
    public void setHumanMajorKindName(String humanMajorKindName) {
        this.humanMajorKindName = humanMajorKindName;
    }

    /**
     * 获取humanMajorId
     * 
     * @return humanMajorId
     */
    public String getHumanMajorId() {
        return this.humanMajorId;
    }

    /**
     * 设置humanMajorId
     * 
     * @param humanMajorId
     */
    public void setHumanMajorId(String humanMajorId) {
        this.humanMajorId = humanMajorId;
    }

    /**
     * 获取hunmaMajorName
     * 
     * @return hunmaMajorName
     */
    public String getHunmaMajorName() {
        return this.hunmaMajorName;
    }

    /**
     * 设置hunmaMajorName
     * 
     * @param hunmaMajorName
     */
    public void setHunmaMajorName(String hunmaMajorName) {
        this.hunmaMajorName = hunmaMajorName;
    }

    /**
     * 获取humanTelephone
     * 
     * @return humanTelephone
     */
    public String getHumanTelephone() {
        return this.humanTelephone;
    }

    /**
     * 设置humanTelephone
     * 
     * @param humanTelephone
     */
    public void setHumanTelephone(String humanTelephone) {
        this.humanTelephone = humanTelephone;
    }

    /**
     * 获取humanMobilephone
     * 
     * @return humanMobilephone
     */
    public String getHumanMobilephone() {
        return this.humanMobilephone;
    }

    /**
     * 设置humanMobilephone
     * 
     * @param humanMobilephone
     */
    public void setHumanMobilephone(String humanMobilephone) {
        this.humanMobilephone = humanMobilephone;
    }

    /**
     * 获取humanBank
     * 
     * @return humanBank
     */
    public String getHumanBank() {
        return this.humanBank;
    }

    /**
     * 设置humanBank
     * 
     * @param humanBank
     */
    public void setHumanBank(String humanBank) {
        this.humanBank = humanBank;
    }

    /**
     * 获取humanAccount
     * 
     * @return humanAccount
     */
    public String getHumanAccount() {
        return this.humanAccount;
    }

    /**
     * 设置humanAccount
     * 
     * @param humanAccount
     */
    public void setHumanAccount(String humanAccount) {
        this.humanAccount = humanAccount;
    }

    /**
     * 获取humanQq
     * 
     * @return humanQq
     */
    public String getHumanQq() {
        return this.humanQq;
    }

    /**
     * 设置humanQq
     * 
     * @param humanQq
     */
    public void setHumanQq(String humanQq) {
        this.humanQq = humanQq;
    }

    /**
     * 获取humanEmail
     * 
     * @return humanEmail
     */
    public String getHumanEmail() {
        return this.humanEmail;
    }

    /**
     * 设置humanEmail
     * 
     * @param humanEmail
     */
    public void setHumanEmail(String humanEmail) {
        this.humanEmail = humanEmail;
    }

    /**
     * 获取humanHobby
     * 
     * @return humanHobby
     */
    public String getHumanHobby() {
        return this.humanHobby;
    }

    /**
     * 设置humanHobby
     * 
     * @param humanHobby
     */
    public void setHumanHobby(String humanHobby) {
        this.humanHobby = humanHobby;
    }

    /**
     * 获取humanSpeciality
     * 
     * @return humanSpeciality
     */
    public String getHumanSpeciality() {
        return this.humanSpeciality;
    }

    /**
     * 设置humanSpeciality
     * 
     * @param humanSpeciality
     */
    public void setHumanSpeciality(String humanSpeciality) {
        this.humanSpeciality = humanSpeciality;
    }

    /**
     * 获取humanSex
     * 
     * @return humanSex
     */
    public String getHumanSex() {
        return this.humanSex;
    }

    /**
     * 设置humanSex
     * 
     * @param humanSex
     */
    public void setHumanSex(String humanSex) {
        this.humanSex = humanSex;
    }

    /**
     * 获取humanReligion
     * 
     * @return humanReligion
     */
    public String getHumanReligion() {
        return this.humanReligion;
    }

    /**
     * 设置humanReligion
     * 
     * @param humanReligion
     */
    public void setHumanReligion(String humanReligion) {
        this.humanReligion = humanReligion;
    }

    /**
     * 获取humanParty
     * 
     * @return humanParty
     */
    public String getHumanParty() {
        return this.humanParty;
    }

    /**
     * 设置humanParty
     * 
     * @param humanParty
     */
    public void setHumanParty(String humanParty) {
        this.humanParty = humanParty;
    }

    /**
     * 获取humanNationality
     * 
     * @return humanNationality
     */
    public String getHumanNationality() {
        return this.humanNationality;
    }

    /**
     * 设置humanNationality
     * 
     * @param humanNationality
     */
    public void setHumanNationality(String humanNationality) {
        this.humanNationality = humanNationality;
    }

    /**
     * 获取humanRace
     * 
     * @return humanRace
     */
    public String getHumanRace() {
        return this.humanRace;
    }

    /**
     * 设置humanRace
     * 
     * @param humanRace
     */
    public void setHumanRace(String humanRace) {
        this.humanRace = humanRace;
    }

    /**
     * 获取humanBirthday
     * 
     * @return humanBirthday
     */
    public Timestamp getHumanBirthday() {
        return this.humanBirthday;
    }

    /**
     * 设置humanBirthday
     * 
     * @param humanBirthday
     */
    public void setHumanBirthday(Timestamp humanBirthday) {
        this.humanBirthday = humanBirthday;
    }

    /**
     * 获取humanBirthplace
     * 
     * @return humanBirthplace
     */
    public String getHumanBirthplace() {
        return this.humanBirthplace;
    }

    /**
     * 设置humanBirthplace
     * 
     * @param humanBirthplace
     */
    public void setHumanBirthplace(String humanBirthplace) {
        this.humanBirthplace = humanBirthplace;
    }

    /**
     * 获取humanAge
     * 
     * @return humanAge
     */
    public Integer getHumanAge() {
        return this.humanAge;
    }

    /**
     * 设置humanAge
     * 
     * @param humanAge
     */
    public void setHumanAge(Integer humanAge) {
        this.humanAge = humanAge;
    }

    /**
     * 获取humanEducatedDegree
     * 
     * @return humanEducatedDegree
     */
    public String getHumanEducatedDegree() {
        return this.humanEducatedDegree;
    }

    /**
     * 设置humanEducatedDegree
     * 
     * @param humanEducatedDegree
     */
    public void setHumanEducatedDegree(String humanEducatedDegree) {
        this.humanEducatedDegree = humanEducatedDegree;
    }

    /**
     * 获取humanEducatedYears
     * 
     * @return humanEducatedYears
     */
    public Integer getHumanEducatedYears() {
        return this.humanEducatedYears;
    }

    /**
     * 设置humanEducatedYears
     * 
     * @param humanEducatedYears
     */
    public void setHumanEducatedYears(Integer humanEducatedYears) {
        this.humanEducatedYears = humanEducatedYears;
    }

    /**
     * 获取humanEducatedMajor
     * 
     * @return humanEducatedMajor
     */
    public String getHumanEducatedMajor() {
        return this.humanEducatedMajor;
    }

    /**
     * 设置humanEducatedMajor
     * 
     * @param humanEducatedMajor
     */
    public void setHumanEducatedMajor(String humanEducatedMajor) {
        this.humanEducatedMajor = humanEducatedMajor;
    }

    /**
     * 获取humanSocietySecurityId
     * 
     * @return humanSocietySecurityId
     */
    public String getHumanSocietySecurityId() {
        return this.humanSocietySecurityId;
    }

    /**
     * 设置humanSocietySecurityId
     * 
     * @param humanSocietySecurityId
     */
    public void setHumanSocietySecurityId(String humanSocietySecurityId) {
        this.humanSocietySecurityId = humanSocietySecurityId;
    }

    /**
     * 获取humanIdCard
     * 
     * @return humanIdCard
     */
    public String getHumanIdCard() {
        return this.humanIdCard;
    }

    /**
     * 设置humanIdCard
     * 
     * @param humanIdCard
     */
    public void setHumanIdCard(String humanIdCard) {
        this.humanIdCard = humanIdCard;
    }

    /**
     * 获取remark
     * 
     * @return remark
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * 设置remark
     * 
     * @param remark
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * 获取salaryStandardId
     * 
     * @return salaryStandardId
     */
    public String getSalaryStandardId() {
        return this.salaryStandardId;
    }

    /**
     * 设置salaryStandardId
     * 
     * @param salaryStandardId
     */
    public void setSalaryStandardId(String salaryStandardId) {
        this.salaryStandardId = salaryStandardId;
    }

    /**
     * 获取salaryStandardName
     * 
     * @return salaryStandardName
     */
    public String getSalaryStandardName() {
        return this.salaryStandardName;
    }

    /**
     * 设置salaryStandardName
     * 
     * @param salaryStandardName
     */
    public void setSalaryStandardName(String salaryStandardName) {
        this.salaryStandardName = salaryStandardName;
    }

    /**
     * 获取salarySum
     * 
     * @return salarySum
     */
    public Double getSalarySum() {
        return this.salarySum;
    }

    /**
     * 设置salarySum
     * 
     * @param salarySum
     */
    public void setSalarySum(Double salarySum) {
        this.salarySum = salarySum;
    }

    /**
     * 获取demandSalaraySum
     * 
     * @return demandSalaraySum
     */
    public Double getDemandSalaraySum() {
        return this.demandSalaraySum;
    }

    /**
     * 设置demandSalaraySum
     * 
     * @param demandSalaraySum
     */
    public void setDemandSalaraySum(Double demandSalaraySum) {
        this.demandSalaraySum = demandSalaraySum;
    }

    /**
     * 获取paidSalarySum
     * 
     * @return paidSalarySum
     */
    public Double getPaidSalarySum() {
        return this.paidSalarySum;
    }

    /**
     * 设置paidSalarySum
     * 
     * @param paidSalarySum
     */
    public void setPaidSalarySum(Double paidSalarySum) {
        this.paidSalarySum = paidSalarySum;
    }

    /**
     * 获取majorChangeAmount
     * 
     * @return majorChangeAmount
     */
    public Integer getMajorChangeAmount() {
        return this.majorChangeAmount;
    }

    /**
     * 设置majorChangeAmount
     * 
     * @param majorChangeAmount
     */
    public void setMajorChangeAmount(Integer majorChangeAmount) {
        this.majorChangeAmount = majorChangeAmount;
    }

    /**
     * 获取bonusAmount
     * 
     * @return bonusAmount
     */
    public Integer getBonusAmount() {
        return this.bonusAmount;
    }

    /**
     * 设置bonusAmount
     * 
     * @param bonusAmount
     */
    public void setBonusAmount(Integer bonusAmount) {
        this.bonusAmount = bonusAmount;
    }

    /**
     * 获取trainingAmount
     * 
     * @return trainingAmount
     */
    public Integer getTrainingAmount() {
        return this.trainingAmount;
    }

    /**
     * 设置trainingAmount
     * 
     * @param trainingAmount
     */
    public void setTrainingAmount(Integer trainingAmount) {
        this.trainingAmount = trainingAmount;
    }

    /**
     * 获取fileChangAmount
     * 
     * @return fileChangAmount
     */
    public Integer getFileChangAmount() {
        return this.fileChangAmount;
    }

    /**
     * 设置fileChangAmount
     * 
     * @param fileChangAmount
     */
    public void setFileChangAmount(Integer fileChangAmount) {
        this.fileChangAmount = fileChangAmount;
    }

    /**
     * 获取humanHistroyRecords
     * 
     * @return humanHistroyRecords
     */
    public String getHumanHistroyRecords() {
        return this.humanHistroyRecords;
    }

    /**
     * 设置humanHistroyRecords
     * 
     * @param humanHistroyRecords
     */
    public void setHumanHistroyRecords(String humanHistroyRecords) {
        this.humanHistroyRecords = humanHistroyRecords;
    }

    /**
     * 获取humanFamilyMembership
     * 
     * @return humanFamilyMembership
     */
    public String getHumanFamilyMembership() {
        return this.humanFamilyMembership;
    }

    /**
     * 设置humanFamilyMembership
     * 
     * @param humanFamilyMembership
     */
    public void setHumanFamilyMembership(String humanFamilyMembership) {
        this.humanFamilyMembership = humanFamilyMembership;
    }

    /**
     * 获取humanPicture
     * 
     * @return humanPicture
     */
    public String getHumanPicture() {
        return this.humanPicture;
    }

    /**
     * 设置humanPicture
     * 
     * @param humanPicture
     */
    public void setHumanPicture(String humanPicture) {
        this.humanPicture = humanPicture;
    }

    /**
     * 获取attachmentName
     * 
     * @return attachmentName
     */
    public String getAttachmentName() {
        return this.attachmentName;
    }

    /**
     * 设置attachmentName
     * 
     * @param attachmentName
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    /**
     * 获取checkStatus
     * 
     * @return checkStatus
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * 设置checkStatus
     * 
     * @param checkStatus
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * 获取register
     * 
     * @return register
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置register
     * 
     * @param register
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取checker
     * 
     * @return checker
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置checker
     * 
     * @param checker
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取changer
     * 
     * @return changer
     */
    public String getChanger() {
        return this.changer;
    }

    /**
     * 设置changer
     * 
     * @param changer
     */
    public void setChanger(String changer) {
        this.changer = changer;
    }

    /**
     * 获取registTime
     * 
     * @return registTime
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置registTime
     * 
     * @param registTime
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取checkTime
     * 
     * @return checkTime
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置checkTime
     * 
     * @param checkTime
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取changeTime
     * 
     * @return changeTime
     */
    public Timestamp getChangeTime() {
        return this.changeTime;
    }

    /**
     * 设置changeTime
     * 
     * @param changeTime
     */
    public void setChangeTime(Timestamp changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * 获取lastlyChangeTime
     * 
     * @return lastlyChangeTime
     */
    public Timestamp getLastlyChangeTime() {
        return this.lastlyChangeTime;
    }

    /**
     * 设置lastlyChangeTime
     * 
     * @param lastlyChangeTime
     */
    public void setLastlyChangeTime(Timestamp lastlyChangeTime) {
        this.lastlyChangeTime = lastlyChangeTime;
    }

    /**
     * 获取deleteTime
     * 
     * @return deleteTime
     */
    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    /**
     * 设置deleteTime
     * 
     * @param deleteTime
     */
    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * 获取recoveryTime
     * 
     * @return recoveryTime
     */
    public Timestamp getRecoveryTime() {
        return this.recoveryTime;
    }

    /**
     * 设置recoveryTime
     * 
     * @param recoveryTime
     */
    public void setRecoveryTime(Timestamp recoveryTime) {
        this.recoveryTime = recoveryTime;
    }

    /**
     * 获取humanFileStatus
     * 
     * @return humanFileStatus
     */
    public Integer getHumanFileStatus() {
        return this.humanFileStatus;
    }

    /**
     * 设置humanFileStatus
     * 
     * @param humanFileStatus
     */
    public void setHumanFileStatus(Integer humanFileStatus) {
        this.humanFileStatus = humanFileStatus;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}