package com.hr.pojo;
import java.sql.Timestamp;
/**
 * MAJOR_CHANGE
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class MajorChange implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5785160952460457527L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** mchId */
    private Integer mchId;

    /** firstKindId */
    private String firstKindId;

    /** firstKindName */
    private String firstKindName;

    /** secondKindId */
    private String secondKindId;

    /** secondKindName */
    private String secondKindName;

    /** thirdKindId */
    private String thirdKindId;

    /** thirdKindName */
    private String thirdKindName;

    /** majorKindId */
    private String majorKindId;

    /** majorKindName */
    private String majorKindName;

    /** majorId */
    private String majorId;

    /** majorName */
    private String majorName;

    /** newFirstKindId */
    private String newFirstKindId;

    /** newFirstKindName */
    private String newFirstKindName;

    /** newSecondKindId */
    private String newSecondKindId;

    /** newSecondKindName */
    private String newSecondKindName;

    /** newThirdKindId */
    private String newThirdKindId;

    /** newThirdKindName */
    private String newThirdKindName;

    /** newMajorKindId */
    private String newMajorKindId;

    /** newMajorKindName */
    private String newMajorKindName;

    /** newMajorId */
    private String newMajorId;

    /** newMajorName */
    private String newMajorName;

    /** humanId */
    private String humanId;

    /** humanName */
    private String humanName;

    /** salaryStandardId */
    private String salaryStandardId;

    /** salaryStandardName */
    private String salaryStandardName;

    /** salarySum */
    private Double salarySum;

    /** newSalaryStandardId */
    private String newSalaryStandardId;

    /** newSalaryStandardName */
    private String newSalaryStandardName;

    /** newSalarySum */
    private Double newSalarySum;

    /** changeReason */
    private String changeReason;

    /** checkReason */
    private String checkReason;

    /** checkStatus */
    private Integer checkStatus;

    /** register */
    private String register;

    /** checker */
    private String checker;

    /** registTime */
    private Timestamp registTime;

    /** checkTime */
    private Timestamp checkTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取mchId
     * 
     * @return mchId
     */
    public Integer getMchId() {
        return this.mchId;
    }

    /**
     * 设置mchId
     * 
     * @param mchId
     */
    public void setMchId(Integer mchId) {
        this.mchId = mchId;
    }

    /**
     * 获取firstKindId
     * 
     * @return firstKindId
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置firstKindId
     * 
     * @param firstKindId
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取firstKindName
     * 
     * @return firstKindName
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置firstKindName
     * 
     * @param firstKindName
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取secondKindId
     * 
     * @return secondKindId
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置secondKindId
     * 
     * @param secondKindId
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取secondKindName
     * 
     * @return secondKindName
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置secondKindName
     * 
     * @param secondKindName
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /**
     * 获取thirdKindId
     * 
     * @return thirdKindId
     */
    public String getThirdKindId() {
        return this.thirdKindId;
    }

    /**
     * 设置thirdKindId
     * 
     * @param thirdKindId
     */
    public void setThirdKindId(String thirdKindId) {
        this.thirdKindId = thirdKindId;
    }

    /**
     * 获取thirdKindName
     * 
     * @return thirdKindName
     */
    public String getThirdKindName() {
        return this.thirdKindName;
    }

    /**
     * 设置thirdKindName
     * 
     * @param thirdKindName
     */
    public void setThirdKindName(String thirdKindName) {
        this.thirdKindName = thirdKindName;
    }

    /**
     * 获取majorKindId
     * 
     * @return majorKindId
     */
    public String getMajorKindId() {
        return this.majorKindId;
    }

    /**
     * 设置majorKindId
     * 
     * @param majorKindId
     */
    public void setMajorKindId(String majorKindId) {
        this.majorKindId = majorKindId;
    }

    /**
     * 获取majorKindName
     * 
     * @return majorKindName
     */
    public String getMajorKindName() {
        return this.majorKindName;
    }

    /**
     * 设置majorKindName
     * 
     * @param majorKindName
     */
    public void setMajorKindName(String majorKindName) {
        this.majorKindName = majorKindName;
    }

    /**
     * 获取majorId
     * 
     * @return majorId
     */
    public String getMajorId() {
        return this.majorId;
    }

    /**
     * 设置majorId
     * 
     * @param majorId
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId;
    }

    /**
     * 获取majorName
     * 
     * @return majorName
     */
    public String getMajorName() {
        return this.majorName;
    }

    /**
     * 设置majorName
     * 
     * @param majorName
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * 获取newFirstKindId
     * 
     * @return newFirstKindId
     */
    public String getNewFirstKindId() {
        return this.newFirstKindId;
    }

    /**
     * 设置newFirstKindId
     * 
     * @param newFirstKindId
     */
    public void setNewFirstKindId(String newFirstKindId) {
        this.newFirstKindId = newFirstKindId;
    }

    /**
     * 获取newFirstKindName
     * 
     * @return newFirstKindName
     */
    public String getNewFirstKindName() {
        return this.newFirstKindName;
    }

    /**
     * 设置newFirstKindName
     * 
     * @param newFirstKindName
     */
    public void setNewFirstKindName(String newFirstKindName) {
        this.newFirstKindName = newFirstKindName;
    }

    /**
     * 获取newSecondKindId
     * 
     * @return newSecondKindId
     */
    public String getNewSecondKindId() {
        return this.newSecondKindId;
    }

    /**
     * 设置newSecondKindId
     * 
     * @param newSecondKindId
     */
    public void setNewSecondKindId(String newSecondKindId) {
        this.newSecondKindId = newSecondKindId;
    }

    /**
     * 获取newSecondKindName
     * 
     * @return newSecondKindName
     */
    public String getNewSecondKindName() {
        return this.newSecondKindName;
    }

    /**
     * 设置newSecondKindName
     * 
     * @param newSecondKindName
     */
    public void setNewSecondKindName(String newSecondKindName) {
        this.newSecondKindName = newSecondKindName;
    }

    /**
     * 获取newThirdKindId
     * 
     * @return newThirdKindId
     */
    public String getNewThirdKindId() {
        return this.newThirdKindId;
    }

    /**
     * 设置newThirdKindId
     * 
     * @param newThirdKindId
     */
    public void setNewThirdKindId(String newThirdKindId) {
        this.newThirdKindId = newThirdKindId;
    }

    /**
     * 获取newThirdKindName
     * 
     * @return newThirdKindName
     */
    public String getNewThirdKindName() {
        return this.newThirdKindName;
    }

    /**
     * 设置newThirdKindName
     * 
     * @param newThirdKindName
     */
    public void setNewThirdKindName(String newThirdKindName) {
        this.newThirdKindName = newThirdKindName;
    }

    /**
     * 获取newMajorKindId
     * 
     * @return newMajorKindId
     */
    public String getNewMajorKindId() {
        return this.newMajorKindId;
    }

    /**
     * 设置newMajorKindId
     * 
     * @param newMajorKindId
     */
    public void setNewMajorKindId(String newMajorKindId) {
        this.newMajorKindId = newMajorKindId;
    }

    /**
     * 获取newMajorKindName
     * 
     * @return newMajorKindName
     */
    public String getNewMajorKindName() {
        return this.newMajorKindName;
    }

    /**
     * 设置newMajorKindName
     * 
     * @param newMajorKindName
     */
    public void setNewMajorKindName(String newMajorKindName) {
        this.newMajorKindName = newMajorKindName;
    }

    /**
     * 获取newMajorId
     * 
     * @return newMajorId
     */
    public String getNewMajorId() {
        return this.newMajorId;
    }

    /**
     * 设置newMajorId
     * 
     * @param newMajorId
     */
    public void setNewMajorId(String newMajorId) {
        this.newMajorId = newMajorId;
    }

    /**
     * 获取newMajorName
     * 
     * @return newMajorName
     */
    public String getNewMajorName() {
        return this.newMajorName;
    }

    /**
     * 设置newMajorName
     * 
     * @param newMajorName
     */
    public void setNewMajorName(String newMajorName) {
        this.newMajorName = newMajorName;
    }

    /**
     * 获取humanId
     * 
     * @return humanId
     */
    public String getHumanId() {
        return this.humanId;
    }

    /**
     * 设置humanId
     * 
     * @param humanId
     */
    public void setHumanId(String humanId) {
        this.humanId = humanId;
    }

    /**
     * 获取humanName
     * 
     * @return humanName
     */
    public String getHumanName() {
        return this.humanName;
    }

    /**
     * 设置humanName
     * 
     * @param humanName
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName;
    }

    /**
     * 获取salaryStandardId
     * 
     * @return salaryStandardId
     */
    public String getSalaryStandardId() {
        return this.salaryStandardId;
    }

    /**
     * 设置salaryStandardId
     * 
     * @param salaryStandardId
     */
    public void setSalaryStandardId(String salaryStandardId) {
        this.salaryStandardId = salaryStandardId;
    }

    /**
     * 获取salaryStandardName
     * 
     * @return salaryStandardName
     */
    public String getSalaryStandardName() {
        return this.salaryStandardName;
    }

    /**
     * 设置salaryStandardName
     * 
     * @param salaryStandardName
     */
    public void setSalaryStandardName(String salaryStandardName) {
        this.salaryStandardName = salaryStandardName;
    }

    /**
     * 获取salarySum
     * 
     * @return salarySum
     */
    public Double getSalarySum() {
        return this.salarySum;
    }

    /**
     * 设置salarySum
     * 
     * @param salarySum
     */
    public void setSalarySum(Double salarySum) {
        this.salarySum = salarySum;
    }

    /**
     * 获取newSalaryStandardId
     * 
     * @return newSalaryStandardId
     */
    public String getNewSalaryStandardId() {
        return this.newSalaryStandardId;
    }

    /**
     * 设置newSalaryStandardId
     * 
     * @param newSalaryStandardId
     */
    public void setNewSalaryStandardId(String newSalaryStandardId) {
        this.newSalaryStandardId = newSalaryStandardId;
    }

    /**
     * 获取newSalaryStandardName
     * 
     * @return newSalaryStandardName
     */
    public String getNewSalaryStandardName() {
        return this.newSalaryStandardName;
    }

    /**
     * 设置newSalaryStandardName
     * 
     * @param newSalaryStandardName
     */
    public void setNewSalaryStandardName(String newSalaryStandardName) {
        this.newSalaryStandardName = newSalaryStandardName;
    }

    /**
     * 获取newSalarySum
     * 
     * @return newSalarySum
     */
    public Double getNewSalarySum() {
        return this.newSalarySum;
    }

    /**
     * 设置newSalarySum
     * 
     * @param newSalarySum
     */
    public void setNewSalarySum(Double newSalarySum) {
        this.newSalarySum = newSalarySum;
    }

    /**
     * 获取changeReason
     * 
     * @return changeReason
     */
    public String getChangeReason() {
        return this.changeReason;
    }

    /**
     * 设置changeReason
     * 
     * @param changeReason
     */
    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason;
    }

    /**
     * 获取checkReason
     * 
     * @return checkReason
     */
    public String getCheckReason() {
        return this.checkReason;
    }

    /**
     * 设置checkReason
     * 
     * @param checkReason
     */
    public void setCheckReason(String checkReason) {
        this.checkReason = checkReason;
    }

    /**
     * 获取checkStatus
     * 
     * @return checkStatus
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * 设置checkStatus
     * 
     * @param checkStatus
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * 获取register
     * 
     * @return register
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置register
     * 
     * @param register
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取checker
     * 
     * @return checker
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置checker
     * 
     * @param checker
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取registTime
     * 
     * @return registTime
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置registTime
     * 
     * @param registTime
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取checkTime
     * 
     * @return checkTime
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置checkTime
     * 
     * @param checkTime
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}