package com.hr.pojo;
/**
 * SALARY_GRANT_DETAILS
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class SalaryGrantDetails implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3400608304216793919L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** grdId */
    private Integer grdId;

    /** salaryGrantId */
    private String salaryGrantId;

    /** humanId */
    private String humanId;

    /** humanName */
    private String humanName;

    /** bounsSum */
    private Double bounsSum;

    /** saleSum */
    private Double saleSum;

    /** deductSum */
    private Double deductSum;

    /** salaryStandardSum */
    private Double salaryStandardSum;

    /** salaryPaidSum */
    private Double salaryPaidSum;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取grdId
     * 
     * @return grdId
     */
    public Integer getGrdId() {
        return this.grdId;
    }

    /**
     * 设置grdId
     * 
     * @param grdId
     */
    public void setGrdId(Integer grdId) {
        this.grdId = grdId;
    }

    /**
     * 获取salaryGrantId
     * 
     * @return salaryGrantId
     */
    public String getSalaryGrantId() {
        return this.salaryGrantId;
    }

    /**
     * 设置salaryGrantId
     * 
     * @param salaryGrantId
     */
    public void setSalaryGrantId(String salaryGrantId) {
        this.salaryGrantId = salaryGrantId;
    }

    /**
     * 获取humanId
     * 
     * @return humanId
     */
    public String getHumanId() {
        return this.humanId;
    }

    /**
     * 设置humanId
     * 
     * @param humanId
     */
    public void setHumanId(String humanId) {
        this.humanId = humanId;
    }

    /**
     * 获取humanName
     * 
     * @return humanName
     */
    public String getHumanName() {
        return this.humanName;
    }

    /**
     * 设置humanName
     * 
     * @param humanName
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName;
    }

    /**
     * 获取bounsSum
     * 
     * @return bounsSum
     */
    public Double getBounsSum() {
        return this.bounsSum;
    }

    /**
     * 设置bounsSum
     * 
     * @param bounsSum
     */
    public void setBounsSum(Double bounsSum) {
        this.bounsSum = bounsSum;
    }

    /**
     * 获取saleSum
     * 
     * @return saleSum
     */
    public Double getSaleSum() {
        return this.saleSum;
    }

    /**
     * 设置saleSum
     * 
     * @param saleSum
     */
    public void setSaleSum(Double saleSum) {
        this.saleSum = saleSum;
    }

    /**
     * 获取deductSum
     * 
     * @return deductSum
     */
    public Double getDeductSum() {
        return this.deductSum;
    }

    /**
     * 设置deductSum
     * 
     * @param deductSum
     */
    public void setDeductSum(Double deductSum) {
        this.deductSum = deductSum;
    }

    /**
     * 获取salaryStandardSum
     * 
     * @return salaryStandardSum
     */
    public Double getSalaryStandardSum() {
        return this.salaryStandardSum;
    }

    /**
     * 设置salaryStandardSum
     * 
     * @param salaryStandardSum
     */
    public void setSalaryStandardSum(Double salaryStandardSum) {
        this.salaryStandardSum = salaryStandardSum;
    }

    /**
     * 获取salaryPaidSum
     * 
     * @return salaryPaidSum
     */
    public Double getSalaryPaidSum() {
        return this.salaryPaidSum;
    }

    /**
     * 设置salaryPaidSum
     * 
     * @param salaryPaidSum
     */
    public void setSalaryPaidSum(Double salaryPaidSum) {
        this.salaryPaidSum = salaryPaidSum;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}