package com.hr.pojo;
import java.sql.Timestamp;

/**
 * SALARY_GRANT
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class SalaryGrant implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 836948990516333081L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** sgrId */
    private Integer sgrId;

    /** salaryGrantId */
    private String salaryGrantId;

    /** salaryStandardId */
    private String salaryStandardId;

    /** firstKindId */
    private String firstKindId;

    /** firstKindName */
    private String firstKindName;

    /** secondKindId */
    private String secondKindId;

    /** secondKindName */
    private String secondKindName;

    /** thirdKindId */
    private String thirdKindId;

    /** thirdKindName */
    private String thirdKindName;

    /** humanAmount */
    private Integer humanAmount;

    /** salaryStandardSum */
    private Double salaryStandardSum;

    /** salaryPaidSum */
    private Double salaryPaidSum;

    /** register */
    private String register;

    /** registTime */
    private Timestamp registTime;

    /** checker */
    private String checker;

    /** checkTime */
    private Timestamp checkTime;

    /** checkStatus */
    private Integer checkStatus;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取sgrId
     * 
     * @return sgrId
     */
    public Integer getSgrId() {
        return this.sgrId;
    }

    /**
     * 设置sgrId
     * 
     * @param sgrId
     */
    public void setSgrId(Integer sgrId) {
        this.sgrId = sgrId;
    }

    /**
     * 获取salaryGrantId
     * 
     * @return salaryGrantId
     */
    public String getSalaryGrantId() {
        return this.salaryGrantId;
    }

    /**
     * 设置salaryGrantId
     * 
     * @param salaryGrantId
     */
    public void setSalaryGrantId(String salaryGrantId) {
        this.salaryGrantId = salaryGrantId;
    }

    /**
     * 获取salaryStandardId
     * 
     * @return salaryStandardId
     */
    public String getSalaryStandardId() {
        return this.salaryStandardId;
    }

    /**
     * 设置salaryStandardId
     * 
     * @param salaryStandardId
     */
    public void setSalaryStandardId(String salaryStandardId) {
        this.salaryStandardId = salaryStandardId;
    }

    /**
     * 获取firstKindId
     * 
     * @return firstKindId
     */
    public String getFirstKindId() {
        return this.firstKindId;
    }

    /**
     * 设置firstKindId
     * 
     * @param firstKindId
     */
    public void setFirstKindId(String firstKindId) {
        this.firstKindId = firstKindId;
    }

    /**
     * 获取firstKindName
     * 
     * @return firstKindName
     */
    public String getFirstKindName() {
        return this.firstKindName;
    }

    /**
     * 设置firstKindName
     * 
     * @param firstKindName
     */
    public void setFirstKindName(String firstKindName) {
        this.firstKindName = firstKindName;
    }

    /**
     * 获取secondKindId
     * 
     * @return secondKindId
     */
    public String getSecondKindId() {
        return this.secondKindId;
    }

    /**
     * 设置secondKindId
     * 
     * @param secondKindId
     */
    public void setSecondKindId(String secondKindId) {
        this.secondKindId = secondKindId;
    }

    /**
     * 获取secondKindName
     * 
     * @return secondKindName
     */
    public String getSecondKindName() {
        return this.secondKindName;
    }

    /**
     * 设置secondKindName
     * 
     * @param secondKindName
     */
    public void setSecondKindName(String secondKindName) {
        this.secondKindName = secondKindName;
    }

    /**
     * 获取thirdKindId
     * 
     * @return thirdKindId
     */
    public String getThirdKindId() {
        return this.thirdKindId;
    }

    /**
     * 设置thirdKindId
     * 
     * @param thirdKindId
     */
    public void setThirdKindId(String thirdKindId) {
        this.thirdKindId = thirdKindId;
    }

    /**
     * 获取thirdKindName
     * 
     * @return thirdKindName
     */
    public String getThirdKindName() {
        return this.thirdKindName;
    }

    /**
     * 设置thirdKindName
     * 
     * @param thirdKindName
     */
    public void setThirdKindName(String thirdKindName) {
        this.thirdKindName = thirdKindName;
    }

    /**
     * 获取humanAmount
     * 
     * @return humanAmount
     */
    public Integer getHumanAmount() {
        return this.humanAmount;
    }

    /**
     * 设置humanAmount
     * 
     * @param humanAmount
     */
    public void setHumanAmount(Integer humanAmount) {
        this.humanAmount = humanAmount;
    }

    /**
     * 获取salaryStandardSum
     * 
     * @return salaryStandardSum
     */
    public Double getSalaryStandardSum() {
        return this.salaryStandardSum;
    }

    /**
     * 设置salaryStandardSum
     * 
     * @param salaryStandardSum
     */
    public void setSalaryStandardSum(Double salaryStandardSum) {
        this.salaryStandardSum = salaryStandardSum;
    }

    /**
     * 获取salaryPaidSum
     * 
     * @return salaryPaidSum
     */
    public Double getSalaryPaidSum() {
        return this.salaryPaidSum;
    }

    /**
     * 设置salaryPaidSum
     * 
     * @param salaryPaidSum
     */
    public void setSalaryPaidSum(Double salaryPaidSum) {
        this.salaryPaidSum = salaryPaidSum;
    }

    /**
     * 获取register
     * 
     * @return register
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置register
     * 
     * @param register
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取registTime
     * 
     * @return registTime
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置registTime
     * 
     * @param registTime
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取checker
     * 
     * @return checker
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置checker
     * 
     * @param checker
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取checkTime
     * 
     * @return checkTime
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置checkTime
     * 
     * @param checkTime
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取checkStatus
     * 
     * @return checkStatus
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * 设置checkStatus
     * 
     * @param checkStatus
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}