package com.hr.pojo;
import java.sql.Timestamp;

/**
 * SALARY_STANDARD
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class SalaryStandard implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2890721741594255160L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ssdId */
    private Integer ssdId;

    /** standardId */
    private String standardId;

    /** standardName */
    private String standardName;

    /** designer */
    private String designer;

    /** register */
    private String register;

    /** checker */
    private String checker;

    /** changer */
    private String changer;

    /** registTime */
    private Timestamp registTime;

    /** checkTime */
    private Timestamp checkTime;

    /** changeTime */
    private Timestamp changeTime;

    /** salarySum */
    private Double salarySum;

    /** checkStatus */
    private Integer checkStatus;

    /** changeStatus */
    private Integer changeStatus;

    /** checkComment */
    private String checkComment;

    /** remark */
    private String remark;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取ssdId
     * 
     * @return ssdId
     */
    public Integer getSsdId() {
        return this.ssdId;
    }

    /**
     * 设置ssdId
     * 
     * @param ssdId
     */
    public void setSsdId(Integer ssdId) {
        this.ssdId = ssdId;
    }

    /**
     * 获取standardId
     * 
     * @return standardId
     */
    public String getStandardId() {
        return this.standardId;
    }

    /**
     * 设置standardId
     * 
     * @param standardId
     */
    public void setStandardId(String standardId) {
        this.standardId = standardId;
    }

    /**
     * 获取standardName
     * 
     * @return standardName
     */
    public String getStandardName() {
        return this.standardName;
    }

    /**
     * 设置standardName
     * 
     * @param standardName
     */
    public void setStandardName(String standardName) {
        this.standardName = standardName;
    }

    /**
     * 获取designer
     * 
     * @return designer
     */
    public String getDesigner() {
        return this.designer;
    }

    /**
     * 设置designer
     * 
     * @param designer
     */
    public void setDesigner(String designer) {
        this.designer = designer;
    }

    /**
     * 获取register
     * 
     * @return register
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置register
     * 
     * @param register
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取checker
     * 
     * @return checker
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置checker
     * 
     * @param checker
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取changer
     * 
     * @return changer
     */
    public String getChanger() {
        return this.changer;
    }

    /**
     * 设置changer
     * 
     * @param changer
     */
    public void setChanger(String changer) {
        this.changer = changer;
    }

    /**
     * 获取registTime
     * 
     * @return registTime
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置registTime
     * 
     * @param registTime
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取checkTime
     * 
     * @return checkTime
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置checkTime
     * 
     * @param checkTime
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取changeTime
     * 
     * @return changeTime
     */
    public Timestamp getChangeTime() {
        return this.changeTime;
    }

    /**
     * 设置changeTime
     * 
     * @param changeTime
     */
    public void setChangeTime(Timestamp changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * 获取salarySum
     * 
     * @return salarySum
     */
    public Double getSalarySum() {
        return this.salarySum;
    }

    /**
     * 设置salarySum
     * 
     * @param salarySum
     */
    public void setSalarySum(Double salarySum) {
        this.salarySum = salarySum;
    }

    /**
     * 获取checkStatus
     * 
     * @return checkStatus
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * 设置checkStatus
     * 
     * @param checkStatus
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * 获取changeStatus
     * 
     * @return changeStatus
     */
    public Integer getChangeStatus() {
        return this.changeStatus;
    }

    /**
     * 设置changeStatus
     * 
     * @param changeStatus
     */
    public void setChangeStatus(Integer changeStatus) {
        this.changeStatus = changeStatus;
    }

    /**
     * 获取checkComment
     * 
     * @return checkComment
     */
    public String getCheckComment() {
        return this.checkComment;
    }

    /**
     * 设置checkComment
     * 
     * @param checkComment
     */
    public void setCheckComment(String checkComment) {
        this.checkComment = checkComment;
    }

    /**
     * 获取remark
     * 
     * @return remark
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * 设置remark
     * 
     * @param remark
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}