package com.hr.pojo;
import java.sql.Timestamp;

/**
 * TRAINING
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class Training implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4703641872267932749L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** traId */
    private Integer traId;

    /** majorKindId */
    private String majorKindId;

    /** majorKindName */
    private String majorKindName;

    /** majorId */
    private String majorId;

    /** majorName */
    private String majorName;

    /** humanId */
    private String humanId;

    /** humanName */
    private String humanName;

    /** trainingItem */
    private String trainingItem;

    /** trainingTime */
    private Timestamp trainingTime;

    /** trainingHour */
    private Integer trainingHour;

    /** trainingDegree */
    private String trainingDegree;

    /** register */
    private String register;

    /** checker */
    private String checker;

    /** registTime */
    private Timestamp registTime;

    /** checkTime */
    private Timestamp checkTime;

    /** checkstatus */
    private Integer checkstatus;

    /** remark */
    private String remark;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取traId
     * 
     * @return traId
     */
    public Integer getTraId() {
        return this.traId;
    }

    /**
     * 设置traId
     * 
     * @param traId
     */
    public void setTraId(Integer traId) {
        this.traId = traId;
    }

    /**
     * 获取majorKindId
     * 
     * @return majorKindId
     */
    public String getMajorKindId() {
        return this.majorKindId;
    }

    /**
     * 设置majorKindId
     * 
     * @param majorKindId
     */
    public void setMajorKindId(String majorKindId) {
        this.majorKindId = majorKindId;
    }

    /**
     * 获取majorKindName
     * 
     * @return majorKindName
     */
    public String getMajorKindName() {
        return this.majorKindName;
    }

    /**
     * 设置majorKindName
     * 
     * @param majorKindName
     */
    public void setMajorKindName(String majorKindName) {
        this.majorKindName = majorKindName;
    }

    /**
     * 获取majorId
     * 
     * @return majorId
     */
    public String getMajorId() {
        return this.majorId;
    }

    /**
     * 设置majorId
     * 
     * @param majorId
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId;
    }

    /**
     * 获取majorName
     * 
     * @return majorName
     */
    public String getMajorName() {
        return this.majorName;
    }

    /**
     * 设置majorName
     * 
     * @param majorName
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * 获取humanId
     * 
     * @return humanId
     */
    public String getHumanId() {
        return this.humanId;
    }

    /**
     * 设置humanId
     * 
     * @param humanId
     */
    public void setHumanId(String humanId) {
        this.humanId = humanId;
    }

    /**
     * 获取humanName
     * 
     * @return humanName
     */
    public String getHumanName() {
        return this.humanName;
    }

    /**
     * 设置humanName
     * 
     * @param humanName
     */
    public void setHumanName(String humanName) {
        this.humanName = humanName;
    }

    /**
     * 获取trainingItem
     * 
     * @return trainingItem
     */
    public String getTrainingItem() {
        return this.trainingItem;
    }

    /**
     * 设置trainingItem
     * 
     * @param trainingItem
     */
    public void setTrainingItem(String trainingItem) {
        this.trainingItem = trainingItem;
    }

    /**
     * 获取trainingTime
     * 
     * @return trainingTime
     */
    public Timestamp getTrainingTime() {
        return this.trainingTime;
    }

    /**
     * 设置trainingTime
     * 
     * @param trainingTime
     */
    public void setTrainingTime(Timestamp trainingTime) {
        this.trainingTime = trainingTime;
    }

    /**
     * 获取trainingHour
     * 
     * @return trainingHour
     */
    public Integer getTrainingHour() {
        return this.trainingHour;
    }

    /**
     * 设置trainingHour
     * 
     * @param trainingHour
     */
    public void setTrainingHour(Integer trainingHour) {
        this.trainingHour = trainingHour;
    }

    /**
     * 获取trainingDegree
     * 
     * @return trainingDegree
     */
    public String getTrainingDegree() {
        return this.trainingDegree;
    }

    /**
     * 设置trainingDegree
     * 
     * @param trainingDegree
     */
    public void setTrainingDegree(String trainingDegree) {
        this.trainingDegree = trainingDegree;
    }

    /**
     * 获取register
     * 
     * @return register
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置register
     * 
     * @param register
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取checker
     * 
     * @return checker
     */
    public String getChecker() {
        return this.checker;
    }

    /**
     * 设置checker
     * 
     * @param checker
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * 获取registTime
     * 
     * @return registTime
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置registTime
     * 
     * @param registTime
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取checkTime
     * 
     * @return checkTime
     */
    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置checkTime
     * 
     * @param checkTime
     */
    public void setCheckTime(Timestamp checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取checkstatus
     * 
     * @return checkstatus
     */
    public Integer getCheckstatus() {
        return this.checkstatus;
    }

    /**
     * 设置checkstatus
     * 
     * @param checkstatus
     */
    public void setCheckstatus(Integer checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * 获取remark
     * 
     * @return remark
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * 设置remark
     * 
     * @param remark
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}