package com.hr.pojo;
/**
 * USERS
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class Users implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1885033382066615830L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** uId */
    private Integer uId;

    /** uName */
    private String uName;

    /** uTrueName */
    private String uTrueName;

    /** uPassword */
    private String uPassword;

    /** makId */
    private Integer makId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取uId
     * 
     * @return uId
     */
    public Integer getUId() {
        return this.uId;
    }

    /**
     * 设置uId
     * 
     * @param uId
     */
    public void setUId(Integer uId) {
        this.uId = uId;
    }

    /**
     * 获取uName
     * 
     * @return uName
     */
    public String getUName() {
        return this.uName;
    }

    /**
     * 设置uName
     * 
     * @param uName
     */
    public void setUName(String uName) {
        this.uName = uName;
    }

    /**
     * 获取uTrueName
     * 
     * @return uTrueName
     */
    public String getUTrueName() {
        return this.uTrueName;
    }

    /**
     * 设置uTrueName
     * 
     * @param uTrueName
     */
    public void setUTrueName(String uTrueName) {
        this.uTrueName = uTrueName;
    }

    /**
     * 获取uPassword
     * 
     * @return uPassword
     */
    public String getUPassword() {
        return this.uPassword;
    }

    /**
     * 设置uPassword
     * 
     * @param uPassword
     */
    public void setUPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * 获取makId
     * 
     * @return makId
     */
    public Integer getMakId() {
        return this.makId;
    }

    /**
     * 设置makId
     * 
     * @param makId
     */
    public void setMakId(Integer makId) {
        this.makId = makId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}