package com.hr.dto;

import java.sql.Timestamp;

/**
 * ENGAGE_EXAM
 * 
 * @author sjh
 * @version 1.0.0 2020-03-10
 */
public class EExam implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -2329926173830606753L;


    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    private Integer exaId;

    /** 考试编号 */
    private String examNumber;

    /** 职能ID */
    private String majorKindId;

    /** 职能名称 */
    private String majorKindName;

    /** 职位ID */
    private String majorId;

    /** 职位名称 */
    private String majorName;

    /** 登记者 */
    private String register;

    /** 登记时间 */
    private Timestamp registTime;

    /** 限制时间 */
    private Integer limiteTime;
    
    private Integer amount;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */


	/**
     * 获取ID
     * 
     * @return ID
     */
    public Integer getExaId() {
        return this.exaId;
    }


	/**
     * 设置ID
     * 
     * @param exaId
     *          ID
     */
    public void setExaId(Integer exaId) {
        this.exaId = exaId;
    }

    /**
     * 获取考试编号
     * 
     * @return 考试编号
     */
    public String getExamNumber() {
        return this.examNumber;
    }

    /**
     * 设置考试编号
     * 
     * @param examNumber
     *          考试编号
     */
    public void setExamNumber(String examNumber) {
        this.examNumber = examNumber;
    }

    /**
     * 获取职能ID
     * 
     * @return 职能ID
     */
    public String getMajorKindId() {
        return this.majorKindId;
    }

    /**
     * 设置职能ID
     * 
     * @param majorKindId
     *          职能ID
     */
    public void setMajorKindId(String majorKindId) {
        this.majorKindId = majorKindId;
    }

    /**
     * 获取职能名称
     * 
     * @return 职能名称
     */
    public String getMajorKindName() {
        return this.majorKindName;
    }

    /**
     * 设置职能名称
     * 
     * @param majorKindName
     *          职能名称
     */
    public void setMajorKindName(String majorKindName) {
        this.majorKindName = majorKindName;
    }

    /**
     * 获取职位ID
     * 
     * @return 职位ID
     */
    public String getMajorId() {
        return this.majorId;
    }

    /**
     * 设置职位ID
     * 
     * @param majorId
     *          职位ID
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId;
    }

    /**
     * 获取职位名称
     * 
     * @return 职位名称
     */
    public String getMajorName() {
        return this.majorName;
    }

    /**
     * 设置职位名称
     * 
     * @param majorName
     *          职位名称
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * 获取登记者
     * 
     * @return 登记者
     */
    public String getRegister() {
        return this.register;
    }

    /**
     * 设置登记者
     * 
     * @param register
     *          登记者
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * 获取登记时间
     * 
     * @return 登记时间
     */
    public Timestamp getRegistTime() {
        return this.registTime;
    }

    /**
     * 设置登记时间
     * 
     * @param registTime
     *          登记时间
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 获取限制时间
     * 
     * @return 限制时间
     */
    public Integer getLimiteTime() {
        return this.limiteTime;
    }

    /**
     * 设置限制时间
     * 
     * @param limiteTime
     *          限制时间
     */
    public void setLimiteTime(Integer limiteTime) {
        this.limiteTime = limiteTime;
    }

    public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}


	@Override
	public String toString() {
		return "EExam [exaId=" + exaId + ", examNumber=" + examNumber + ", majorKindId=" + majorKindId
				+ ", majorKindName=" + majorKindName + ", majorId=" + majorId + ", majorName=" + majorName
				+ ", register=" + register + ", registTime=" + registTime + ", limiteTime=" + limiteTime + ", amount="
				+ amount + "]";
	}
    
}
